package logic;

public enum Commands {
	NEW_SINGLE_RESERVATION,
	ENTER_WAITING_LIST,
	CHECK_AVAILABILITY_SINGLE_RESERVATION,
	FREE_SLOTS_DATA,
	CONFIRMATION_SINGLE_RESERVATION,
	PREPAYMENT,
	NEW_GROUP_RESERVATION,
	CONFIRMATION_GROUP_RESERVATION,
	CHECK_ID_PASSWORD,
	Logout,
}
